const actionTypes = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    CONFIGURATION_GET_REQUEST: 'CONFIGURATION_GET_REQUEST',
    CONFIGURATION_GET_SUCCESS: 'CONFIGURATION_GET_SUCCESS',
    CONFIGURATION_GET_FAILURE: 'CONFIGURATION_GET_FAILURE',
}

export default actionTypes;